# Generated by the openapi3 package: do not edit by hand
# Source: openapi.yaml

#' Street routing from one to many places or many to one.
#' The order in the response array corresponds to the order of coordinates of the `many` parameter in the query.
#'
#' @param one geo location as latitude;longitude
#' 
#' @param many geo locations as latitude;longitude,latitude;longitude,...
#' 
#' @param mode routing profile to use (currently supported: `WALK`, `BIKE`, `CAR`)
#' 
#'
#' Allowed values: WALK, BIKE, RENTAL, CAR, CAR_PARKING, CAR_DROPOFF, ODM, FLEX, TRANSIT, TRAM, SUBWAY, FERRY, AIRPLANE, METRO, BUS, COACH, RAIL, HIGHSPEED_RAIL, LONG_DISTANCE, NIGHT_RAIL, REGIONAL_FAST_RAIL, REGIONAL_RAIL, CABLE_CAR, FUNICULAR, AREAL_LIFT, OTHER.
#' @param max maximum travel time in seconds
#' 
#' @param maxMatchingDistance maximum matching distance in meters to match geo coordinates to the street network
#' 
#' @param elevationCosts Optional. Default is `NONE`.
#' 
#' Set an elevation cost profile, to penalize routes with incline.
#' - `NONE`: No additional costs for elevations. This is the default behavior
#' - `LOW`: Add a low cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if small detours are required.
#' - `HIGH`: Add a high cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if larger detours are required.
#' 
#' As using an elevation costs profile will increase the travel duration,
#' routing through steep terrain may exceed the maximal allowed duration,
#' causing a location to appear unreachable.
#' Increasing the maximum travel time for these segments may resolve this issue.
#' 
#' Elevation cost profiles are currently used by following street modes:
#' - `BIKE`
#'
#' Allowed values: NONE, LOW, HIGH.
#' @param arriveBy true = many to one
#' false = one to many
#' @param .return_as How to return the response. One of 'list' (default), 'string', or 'raw'.
#' @param .json_parser JSON parser when `.return_as = 'list'`. One of 'RcppSimdJson' (default) or 'jsonlite'.
#' @param .headers Named list of additional HTTP headers to include.
#' @param .auth Bearer token string or a function `function(req) req` to apply custom auth.
#' @param .throttle_rate Requests per second (numeric). If set, throttling is applied.
#' @param .build_only If TRUE, return the unperformed request object.
#' @param .server Override the server URL for this call.
#' @param .endpoint A string to override the path for this specific request (e.g., '/v2/users/{id}'). If provided, it will be used instead of the default path from the specification.
#' @param .referer Optional Referer header value.
#' @param .req_options Named list of curl options passed to `httr2::req_options()`.
#' @param .handle_response Optional function `function(resp) ...` to post-process the response.
#' @param .json_auto_unbox If TRUE (default), auto-unbox scalar JSON values for request bodies.
#' @export
mc_oneToMany <- function(one = NULL, many = NULL, mode = NULL, max = NULL, maxMatchingDistance = NULL, elevationCosts = NULL, arriveBy = NULL, .return_as = NULL, .json_parser = NULL, .headers = NULL, .auth = NULL, .throttle_rate = NULL, .build_only = NULL, .server = NULL, .endpoint = NULL, .referer = NULL, .req_options = NULL, .handle_response = NULL, .json_auto_unbox = NULL) {
  # --- Self-contained Default Arguments ---
  default_return_as <- "raw"
  default_json_parser <- "RcppSimdJson"
  default_headers <- list(Accept = "*/*")
  default_auth <- NULL
  default_throttle_rate <- NULL
  default_build_only <- TRUE
  default_server <- "http://localhost:8080"
  default_referer <- NULL
  default_req_options <- NULL
  default_json_auto_unbox <- TRUE
  default_handle_response <- NULL

  # --- Request building ---
  server_url <- .server %||% default_server
  req <- httr2::request(server_url)
  req <- httr2::req_method(req, method = "GET")

  # Path parameters
  path_params <- list()
  path_template <- .endpoint %||% "/api/v1/one-to-many"
  if (length(path_params)) {
    # URL-encode each path value
    for (nm in names(path_params)) path_params[[nm]] <- curl::curl_escape(as.character(path_params[[nm]]))
  }
  path_expanded <- as.character(glue::glue_data(path_params, path_template))
  req <- httr2::req_url_path_append(req, path_expanded)

  # Query parameters
  query_params <- list()
  if (!is.null(one)) query_params[['one']] <- one
  if (!is.null(many)) query_params[['many']] <- many
  if (!is.null(mode)) query_params[['mode']] <- mode
  if (!is.null(max)) query_params[['max']] <- max
  if (!is.null(maxMatchingDistance)) query_params[['maxMatchingDistance']] <- maxMatchingDistance
  if (!is.null(elevationCosts)) query_params[['elevationCosts']] <- elevationCosts
  if (!is.null(arriveBy)) query_params[['arriveBy']] <- arriveBy
  if (length(query_params) > 0) {
    req <- do.call(httr2::req_url_query, c(list(req), query_params))
  }



  # --- Control arguments ---
  auth <- .auth %||% default_auth
  if (!is.null(auth)) {
    if (is.character(auth)) {
      req <- httr2::req_auth_bearer_token(req, auth)
    } else if (is.function(auth)) {
      req <- auth(req)
    } else {
      stop('`.auth` must be a token string or a function(req) that returns a request.', call. = FALSE)
    }
  }

  headers <- default_headers
  if (!is.null(.headers)) headers <- c(headers, .headers)
  if (!is.null(headers)) req <- do.call(httr2::req_headers, c(list(req), headers))
  # Ensure Accept exists
  if (is.null(headers) || !any(tolower(names(headers)) == 'accept')) req <- httr2::req_headers(req, Accept = '*/*')

  referer <- .referer %||% default_referer
  if (!is.null(referer)) req <- httr2::req_headers(req, Referer = referer)

  throttle_rate <- .throttle_rate %||% default_throttle_rate
  if (!is.null(throttle_rate)) req <- httr2::req_throttle(req, rate = throttle_rate)

  req_opts <- .req_options %||% default_req_options
  if (!is.null(req_opts)) {
    if (!is.list(req_opts)) stop('`.req_options` must be a named list.', call. = FALSE)
    req <- do.call(httr2::req_options, c(list(req), req_opts))
  }

  build_only <- .build_only %||% default_build_only
  if (isTRUE(build_only)) return(req)

  resp <- httr2::req_perform(req)

  handler <- .handle_response %||% default_handle_response
  if (!is.null(handler) && is.function(handler)) return(handler(resp))

  # Robust response handling
  return_as <- .return_as %||% default_return_as
  return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
  json_parser <- .json_parser %||% default_json_parser
  json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
  switch(return_as,
    'raw' = return(resp),
    'string' = return(httr2::resp_body_string(resp)),
    'list' = switch(
      json_parser,
      'RcppSimdJson' = {
        if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
          return(httr2::resp_body_json(resp))
        }
        RcppSimdJson::fparse(httr2::resp_body_string(resp))
      },
      'jsonlite' = httr2::resp_body_json(resp),
      stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
    ),
    stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
  )
}

