# Generated by the openapi3 package: do not edit by hand
# Source: openapi.yaml

#' Computes optimal connections from one place to another.
#'
#' @param fromPlace `latitude,longitude[,level]` tuple with
#' - latitude and longitude in degrees
#' - (optional) level: the OSM level (default: 0)
#' 
#' OR
#' 
#' stop id
#' @param toPlace `latitude,longitude[,level]` tuple with
#' - latitude and longitude in degrees
#' - (optional) level: the OSM level (default: 0)
#' 
#' OR
#' 
#' stop id
#' @param via List of via stops to visit (only stop IDs, no coordinates allowed for now).
#' Also see the optional parameter `viaMinimumStay` to set a set a minimum stay duration for each via stop.
#' @param viaMinimumStay Optional. If not set, the default is `0,0` - no stay required.
#' 
#' For each `via` stop a minimum stay duration in minutes.
#' 
#' The value `0` signals that it's allowed to stay in the same trip.
#' This enables via stays without counting a transfer and can lead
#' to better connections with less transfers. Transfer connections can
#' still be found with `viaMinimumStay=0`.
#' @param time Optional. Defaults to the current time.
#' 
#' Departure time ($arriveBy=false) / arrival date ($arriveBy=true),
#' @param maxTransfers The maximum number of allowed transfers (i.e. interchanges between transit legs,
#' pre- and postTransit do not count as transfers).
#' `maxTransfers=0` searches for direct transit connections without any transfers.
#' If you want to search only for non-transit connections (`FOOT`, `CAR`, etc.),
#' send an empty `transitModes` parameter instead.
#' 
#' If not provided, the routing uses the server-side default value
#' which is hardcoded and very high to cover all use cases.
#' 
#' *Warning*: Use with care. Setting this too low can lead to
#' optimal (e.g. the fastest) journeys not being found.
#' If this value is too low to reach the destination at all,
#' it can lead to slow routing performance.
#' 
#' In plan endpoints before v3, the behavior is off by one,
#' i.e. `maxTransfers=0` only returns non-transit connections.
#' @param maxTravelTime The maximum travel time in minutes.
#' If not provided, the routing to uses the value
#' hardcoded in the server which is usually quite high.
#' 
#' *Warning*: Use with care. Setting this too low can lead to
#' optimal (e.g. the least transfers) journeys not being found.
#' If this value is too low to reach the destination at all,
#' it can lead to slow routing performance.
#' @param minTransferTime Optional. Default is 0 minutes.
#' 
#' Minimum transfer time for each transfer in minutes.
#' @param additionalTransferTime Optional. Default is 0 minutes.
#' 
#' Additional transfer time reserved for each transfer in minutes.
#' @param transferTimeFactor Optional. Default is 1.0
#' 
#' Factor to multiply minimum required transfer times with.
#' Values smaller than 1.0 are not supported.
#' @param maxMatchingDistance Optional. Default is 25 meters.
#' 
#' Maximum matching distance in meters to match geo coordinates to the street network.
#' @param pedestrianProfile Optional. Default is `FOOT`.
#' 
#' Accessibility profile to use for pedestrian routing in transfers
#' between transit connections, on the first mile, and last mile.
#'
#' Allowed values: FOOT, WHEELCHAIR.
#' @param pedestrianSpeed Optional
#' 
#' Average speed for pedestrian routing.
#' @param cyclingSpeed Optional
#' 
#' Average speed for bike routing.
#' @param elevationCosts Optional. Default is `NONE`.
#' 
#' Set an elevation cost profile, to penalize routes with incline.
#' - `NONE`: No additional costs for elevations. This is the default behavior
#' - `LOW`: Add a low cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if small detours are required.
#' - `HIGH`: Add a high cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if larger detours are required.
#' 
#' As using an elevation costs profile will increase the travel duration,
#' routing through steep terrain may exceed the maximal allowed duration,
#' causing a location to appear unreachable.
#' Increasing the maximum travel time for these segments may resolve this issue.
#' 
#' The profile is used for direct routing, on the first mile, and last mile.
#' 
#' Elevation cost profiles are currently used by following street modes:
#' - `BIKE`
#'
#' Allowed values: NONE, LOW, HIGH.
#' @param useRoutedTransfers Optional. Default is `false`.
#' 
#' Whether to use transfers routed on OpenStreetMap data.
#' @param detailedTransfers - true: Compute transfer polylines and step instructions.
#' - false: Only return basic information (start time, end time, duration) for transfers.
#' @param joinInterlinedLegs Optional. Default is `true`.
#' 
#' Controls if a journey section with stay-seated transfers is returned:
#' - `joinInterlinedLegs=false`: as several legs (full information about all trip numbers, headsigns, etc.).
#' Legs that do not require a transfer (stay-seated transfer) are marked with `interlineWithPreviousLeg=true`.
#' - `joinInterlinedLegs=true` (default behavior): as only one joined leg containing all stops
#' @param transitModes Optional. Default is `TRANSIT` which allows all transit modes (no restriction).
#' Allowed modes for the transit part. If empty, no transit connections will be computed.
#' For example, this can be used to allow only `SUBURBAN,SUBWAY,TRAM`.
#'
#' Allowed values: WALK, BIKE, RENTAL, CAR, CAR_PARKING, CAR_DROPOFF, ODM, RIDE_SHARING, FLEX, DEBUG_BUS_ROUTE, DEBUG_RAILWAY_ROUTE, DEBUG_FERRY_ROUTE, TRANSIT, TRAM, SUBWAY, FERRY, AIRPLANE, BUS, COACH, RAIL, HIGHSPEED_RAIL, LONG_DISTANCE, NIGHT_RAIL, REGIONAL_FAST_RAIL, REGIONAL_RAIL, SUBURBAN, FUNICULAR, AERIAL_LIFT, OTHER, AREAL_LIFT, METRO, CABLE_CAR.
#' @param directModes Optional. Default is `WALK` which will compute walking routes as direct connections.
#' 
#' Modes used for direction connections from start to destination without using transit.
#' Results will be returned on the `direct` key.
#' 
#' Note: Direct connections will only be returned on the first call. For paging calls, they can be omitted.
#' 
#' Note: Transit connections that are slower than the fastest direct connection will not show up.
#' This is being used as a cut-off during transit routing to speed up the search.
#' To prevent this, it's possible to send two separate requests (one with only `transitModes` and one with only `directModes`).
#' 
#' Note: the output `direct` array will stay empty if the input param `maxDirectTime` makes any direct trip impossible.
#' 
#' Only non-transit modes such as `WALK`, `BIKE`, `CAR`, `BIKE_SHARING`, etc. can be used.
#'
#' Allowed values: WALK, BIKE, RENTAL, CAR, CAR_PARKING, CAR_DROPOFF, ODM, RIDE_SHARING, FLEX, DEBUG_BUS_ROUTE, DEBUG_RAILWAY_ROUTE, DEBUG_FERRY_ROUTE, TRANSIT, TRAM, SUBWAY, FERRY, AIRPLANE, BUS, COACH, RAIL, HIGHSPEED_RAIL, LONG_DISTANCE, NIGHT_RAIL, REGIONAL_FAST_RAIL, REGIONAL_RAIL, SUBURBAN, FUNICULAR, AERIAL_LIFT, OTHER, AREAL_LIFT, METRO, CABLE_CAR.
#' @param preTransitModes Optional. Default is `WALK`. Only applies if the `from` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directModes`).
#' 
#' A list of modes that are allowed to be used from the `from` coordinate to the first transit stop. Example: `WALK,BIKE_SHARING`.
#'
#' Allowed values: WALK, BIKE, RENTAL, CAR, CAR_PARKING, CAR_DROPOFF, ODM, RIDE_SHARING, FLEX, DEBUG_BUS_ROUTE, DEBUG_RAILWAY_ROUTE, DEBUG_FERRY_ROUTE, TRANSIT, TRAM, SUBWAY, FERRY, AIRPLANE, BUS, COACH, RAIL, HIGHSPEED_RAIL, LONG_DISTANCE, NIGHT_RAIL, REGIONAL_FAST_RAIL, REGIONAL_RAIL, SUBURBAN, FUNICULAR, AERIAL_LIFT, OTHER, AREAL_LIFT, METRO, CABLE_CAR.
#' @param postTransitModes Optional. Default is `WALK`. Only applies if the `to` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directModes`).
#' 
#' A list of modes that are allowed to be used from the last transit stop to the `to` coordinate. Example: `WALK,BIKE_SHARING`.
#'
#' Allowed values: WALK, BIKE, RENTAL, CAR, CAR_PARKING, CAR_DROPOFF, ODM, RIDE_SHARING, FLEX, DEBUG_BUS_ROUTE, DEBUG_RAILWAY_ROUTE, DEBUG_FERRY_ROUTE, TRANSIT, TRAM, SUBWAY, FERRY, AIRPLANE, BUS, COACH, RAIL, HIGHSPEED_RAIL, LONG_DISTANCE, NIGHT_RAIL, REGIONAL_FAST_RAIL, REGIONAL_RAIL, SUBURBAN, FUNICULAR, AERIAL_LIFT, OTHER, AREAL_LIFT, METRO, CABLE_CAR.
#' @param directRentalFormFactors Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies to direct connections.
#' 
#' A list of vehicle type form factors that are allowed to be used for direct connections.
#' If empty (the default), all form factors are allowed.
#' Example: `BICYCLE,SCOOTER_STANDING`.
#'
#' Allowed values: BICYCLE, CARGO_BICYCLE, CAR, MOPED, SCOOTER_STANDING, SCOOTER_SEATED, OTHER.
#' @param preTransitRentalFormFactors Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `from` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalFormFactors`).
#' 
#' A list of vehicle type form factors that are allowed to be used from the `from` coordinate to the first transit stop.
#' If empty (the default), all form factors are allowed.
#' Example: `BICYCLE,SCOOTER_STANDING`.
#'
#' Allowed values: BICYCLE, CARGO_BICYCLE, CAR, MOPED, SCOOTER_STANDING, SCOOTER_SEATED, OTHER.
#' @param postTransitRentalFormFactors Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `to` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalFormFactors`).
#' 
#' A list of vehicle type form factors that are allowed to be used from the last transit stop to the `to` coordinate.
#' If empty (the default), all form factors are allowed.
#' Example: `BICYCLE,SCOOTER_STANDING`.
#'
#' Allowed values: BICYCLE, CARGO_BICYCLE, CAR, MOPED, SCOOTER_STANDING, SCOOTER_SEATED, OTHER.
#' @param directRentalPropulsionTypes Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies to direct connections.
#' 
#' A list of vehicle type form factors that are allowed to be used for direct connections.
#' If empty (the default), all propulsion types are allowed.
#' Example: `HUMAN,ELECTRIC,ELECTRIC_ASSIST`.
#'
#' Allowed values: HUMAN, ELECTRIC_ASSIST, ELECTRIC, COMBUSTION, COMBUSTION_DIESEL, HYBRID, PLUG_IN_HYBRID, HYDROGEN_FUEL_CELL.
#' @param preTransitRentalPropulsionTypes Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `from` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalPropulsionTypes`).
#' 
#' A list of vehicle propulsion types that are allowed to be used from the `from` coordinate to the first transit stop.
#' If empty (the default), all propulsion types are allowed.
#' Example: `HUMAN,ELECTRIC,ELECTRIC_ASSIST`.
#'
#' Allowed values: HUMAN, ELECTRIC_ASSIST, ELECTRIC, COMBUSTION, COMBUSTION_DIESEL, HYBRID, PLUG_IN_HYBRID, HYDROGEN_FUEL_CELL.
#' @param postTransitRentalPropulsionTypes Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `to` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalPropulsionTypes`).
#' 
#' A list of vehicle propulsion types that are allowed to be used from the last transit stop to the `to` coordinate.
#' If empty (the default), all propulsion types are allowed.
#' Example: `HUMAN,ELECTRIC,ELECTRIC_ASSIST`.
#'
#' Allowed values: HUMAN, ELECTRIC_ASSIST, ELECTRIC, COMBUSTION, COMBUSTION_DIESEL, HYBRID, PLUG_IN_HYBRID, HYDROGEN_FUEL_CELL.
#' @param directRentalProviders Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies to direct connections.
#' 
#' A list of rental providers that are allowed to be used for direct connections.
#' If empty (the default), all providers are allowed.
#' @param directRentalProviderGroups Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies to direct connections.
#' 
#' A list of rental provider groups that are allowed to be used for direct connections.
#' If empty (the default), all providers are allowed.
#' @param preTransitRentalProviders Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `from` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalProviders`).
#' 
#' A list of rental providers that are allowed to be used from the `from` coordinate to the first transit stop.
#' If empty (the default), all providers are allowed.
#' @param preTransitRentalProviderGroups Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `from` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalProviderGroups`).
#' 
#' A list of rental provider groups that are allowed to be used from the `from` coordinate to the first transit stop.
#' If empty (the default), all providers are allowed.
#' @param postTransitRentalProviders Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `to` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalProviders`).
#' 
#' A list of rental providers that are allowed to be used from the last transit stop to the `to` coordinate.
#' If empty (the default), all providers are allowed.
#' @param postTransitRentalProviderGroups Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Only applies if the `to` place is a coordinate (not a transit stop). Does not apply to direct connections (see `directRentalProviderGroups`).
#' 
#' A list of rental provider groups that are allowed to be used from the last transit stop to the `to` coordinate.
#' If empty (the default), all providers are allowed.
#' @param ignoreDirectRentalReturnConstraints Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Default is `false`.
#' 
#' If set to `true`, the routing will ignore rental return constraints for direct connections,
#' allowing the rental vehicle to be parked anywhere.
#' @param ignorePreTransitRentalReturnConstraints Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Default is `false`.
#' 
#' If set to `true`, the routing will ignore rental return constraints for the part from the `from` coordinate to the first transit stop,
#' allowing the rental vehicle to be parked anywhere.
#' @param ignorePostTransitRentalReturnConstraints Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Default is `false`.
#' 
#' If set to `true`, the routing will ignore rental return constraints for the part from the last transit stop to the `to` coordinate,
#' allowing the rental vehicle to be parked anywhere.
#' @param numItineraries The minimum number of itineraries to compute.
#' This is only relevant if `timetableView=true`.
#' The default value is 5.
#' @param maxItineraries Optional. By default all computed itineraries will be returned
#' 
#' The maximum number of itineraries to compute.
#' This is only relevant if `timetableView=true`.
#' 
#' Note: With the current implementation, setting this to a lower
#' number will not result in any speedup.
#' 
#' Note: The number of returned itineraries might be slightly higher
#' than `maxItineraries` as there might be several itineraries with
#' the same departure time but different number of transfers. In order
#' to not miss any itineraries for paging, either none or all
#' itineraries with the same departure time have to be returned.
#' @param pageCursor Use the cursor to go to the next "page" of itineraries.
#' Copy the cursor from the last response and keep the original request as is.
#' This will enable you to search for itineraries in the next or previous time-window.
#' @param timetableView Optional. Default is `true`.
#' 
#' Search for the best trip options within a time window.
#' If true two itineraries are considered optimal
#' if one is better on arrival time (earliest wins)
#' and the other is better on departure time (latest wins).
#' In combination with arriveBy this parameter cover the following use cases:
#' 
#' `timetable=false` = waiting for the first transit departure/arrival is considered travel time:
#' - `arriveBy=true`: event (e.g. a meeting) starts at 10:00 am,
#' compute the best journeys that arrive by that time (maximizes departure time)
#' - `arriveBy=false`: event (e.g. a meeting) ends at 11:00 am,
#' compute the best journeys that depart after that time
#' 
#' `timetable=true` = optimize "later departure" + "earlier arrival" and give all options over a time window:
#' - `arriveBy=true`: the time window around `date` and `time` refers to the arrival time window
#' - `arriveBy=false`: the time window around `date` and `time` refers to the departure time window
#' @param arriveBy Optional. Default is `false`.
#' 
#' - `arriveBy=true`: the parameters `date` and `time` refer to the arrival time
#' - `arriveBy=false`: the parameters `date` and `time` refer to the departure time
#' @param searchWindow Optional. Default is 15 minutes which is `900`.
#' 
#' The length of the search-window in seconds. Default value 15 minutes.
#' 
#' - `arriveBy=true`: number of seconds between the earliest departure time and latest departure time
#' - `arriveBy=false`: number of seconds between the earliest arrival time and the latest arrival time
#' @param requireBikeTransport Optional. Default is `false`.
#' 
#' If set to `true`, all used transit trips are required to allow bike carriage.
#' @param requireCarTransport Optional. Default is `false`.
#' 
#' If set to `true`, all used transit trips are required to allow car carriage.
#' @param maxPreTransitTime Optional. Default is 15min which is `900`.
#' Maximum time in seconds for the first street leg.
#' Is limited by server config variable `street_routing_max_prepost_transit_seconds`.
#' @param maxPostTransitTime Optional. Default is 15min which is `900`.
#' Maximum time in seconds for the last street leg.
#' Is limited by server config variable `street_routing_max_prepost_transit_seconds`.
#' @param maxDirectTime Optional. Default is 30min which is `1800`.
#' Maximum time in seconds for direct connections.
#' Is limited by server config variable `street_routing_max_direct_seconds`.
#' @param fastestDirectFactor Optional. Experimental. Default is `1.0`.
#' Factor with which the duration of the fastest direct non-public-transit connection is multiplied.
#' Values > 1.0 allow transit connections that are slower than the fastest direct non-public-transit connection to be found.
#' @param timeout Optional. Query timeout in seconds.
#' 
#' @param passengers Optional. Experimental. Number of passengers (e.g. for ODM or price calculation)
#' 
#' @param luggage Optional. Experimental. Number of luggage pieces; base unit: airline cabin luggage (e.g. for ODM or price calculation)
#' 
#' @param slowDirect Optional. Experimental. Adds overtaken direct public transit connections.
#' 
#' @param fastestSlowDirectFactor Optional.
#' Factor with which the duration of the fastest slowDirect connection is multiplied.
#' Values > 1.0 allow connections that are slower than the fastest direct transit connection to be found.
#' Values < 1.0 will return all slowDirect connections.
#' @param withFares Optional. Experimental. If set to true, the response will contain fare information.
#' 
#' @param withScheduledSkippedStops Optional. Include intermediate stops where passengers can not alight/board according to schedule.
#' 
#' @param language language tags as used in OpenStreetMap / GTFS
#' (usually BCP-47 / ISO 639-1, or ISO 639-2 if there's no ISO 639-1)
#' @param algorithm algorithm to use
#' 
#'
#' Allowed values: RAPTOR, PONG, TB.
#' @param .return_as A string specifying the return format. Defaults to 'list'. Options are 'list' for a parsed R list, 'raw' for the raw httr2_response object, or 'string' for the raw JSON string.
#' @param .json_parser A string specifying which parser to use when .return_as = 'list'. Defaults to 'RcppSimdJson' (faster) or 'jsonlite'. Beware that their output may differ slightly.
#' @param .headers A named list of extra HTTP headers to add to the request. If no 'Accept' header is provided anywhere, 'Accept: */*' will be sent by default.
#' @param .auth An authentication token or method (e.g., a bearer token string).
#' @param .throttle_rate A number to pass to `httr2::req_throttle()` to limit the rate of requests. For example, `15/60` means 15 requests per minute. This overrides any default rate set at client generation time.
#' @param .build_only A logical. If TRUE, the function will build and return the httr2_request object without performing it. Defaults to FALSE.
#' @param .server A string to override the base URL for this specific request. If provided, it will be used instead of the default server URL.
#' @param .endpoint A string to override the path for this specific request. If provided, it will be used instead of the default path from the specification. For example, use '/v2/users' to override the endpoint path.
#' @param .referer A string to set the Referer HTTP header.
#' @param .req_options A named list of curl options passed to `httr2::req_options()`. Useful for timeouts, proxies, SSL, etc.
#' @param .handle_response A function taking an `httr2_response` and returning a value. If supplied, it overrides `.return_as` / `.json_parser` handling. See helpers like `oa3_content_or_stop()`.
#' @param .json_auto_unbox Logical. If TRUE, JSON bodies are encoded with `auto_unbox = TRUE` (jsonlite). Defaults to FALSE unless overridden.
#' @param .paginate A logical, character string, or function to enable pagination. If TRUE (or "link_header"), uses Link headers. Other options: "page_param", "cursor_param", or a custom function. See `oa3_paginate()`.
#' @export
mc_plan <- function(fromPlace = NULL, toPlace = NULL, via = NULL, viaMinimumStay = NULL, time = NULL, maxTransfers = NULL, maxTravelTime = NULL, minTransferTime = NULL, additionalTransferTime = NULL, transferTimeFactor = NULL, maxMatchingDistance = NULL, pedestrianProfile = NULL, pedestrianSpeed = NULL, cyclingSpeed = NULL, elevationCosts = NULL, useRoutedTransfers = NULL, detailedTransfers = NULL, joinInterlinedLegs = NULL, transitModes = NULL, directModes = NULL, preTransitModes = NULL, postTransitModes = NULL, directRentalFormFactors = NULL, preTransitRentalFormFactors = NULL, postTransitRentalFormFactors = NULL, directRentalPropulsionTypes = NULL, preTransitRentalPropulsionTypes = NULL, postTransitRentalPropulsionTypes = NULL, directRentalProviders = NULL, directRentalProviderGroups = NULL, preTransitRentalProviders = NULL, preTransitRentalProviderGroups = NULL, postTransitRentalProviders = NULL, postTransitRentalProviderGroups = NULL, ignoreDirectRentalReturnConstraints = NULL, ignorePreTransitRentalReturnConstraints = NULL, ignorePostTransitRentalReturnConstraints = NULL, numItineraries = NULL, maxItineraries = NULL, pageCursor = NULL, timetableView = NULL, arriveBy = NULL, searchWindow = NULL, requireBikeTransport = NULL, requireCarTransport = NULL, maxPreTransitTime = NULL, maxPostTransitTime = NULL, maxDirectTime = NULL, fastestDirectFactor = NULL, timeout = NULL, passengers = NULL, luggage = NULL, slowDirect = NULL, fastestSlowDirectFactor = NULL, withFares = NULL, withScheduledSkippedStops = NULL, language = NULL, algorithm = NULL, .return_as = NULL, .json_parser = NULL, .headers = NULL, .auth = NULL, .throttle_rate = NULL, .build_only = NULL, .server = NULL, .endpoint = NULL, .referer = NULL, .req_options = NULL, .handle_response = NULL, .json_auto_unbox = NULL, .paginate = NULL) {
  # --- Self-contained Default Arguments ---
  default_return_as <- "raw"
  default_json_parser <- "RcppSimdJson"
  default_headers <- list(Accept = "*/*")
  default_auth <- NULL
  default_throttle_rate <- NULL
  default_build_only <- TRUE
  default_server <- "http://localhost:8080"
  default_referer <- NULL
  default_req_options <- NULL
  default_json_auto_unbox <- TRUE
  default_handle_response <- NULL

  # --- Request building ---
  server_url <- .server %||% default_server
  req <- httr2::request(server_url)
  req <- httr2::req_method(req, method = "GET")

  # Path parameters
  path_params <- list()
  path_template <- .endpoint %||% "/api/v5/plan"
  if (length(path_params)) {
    # URL-encode each path value
    for (nm in names(path_params)) path_params[[nm]] <- curl::curl_escape(as.character(path_params[[nm]]))
  }
  path_expanded <- as.character(glue::glue_data(path_params, path_template))
  req <- httr2::req_url_path_append(req, path_expanded)

  # Query parameters
  query_params <- list()
  if (!is.null(fromPlace)) query_params[['fromPlace']] <- fromPlace
  if (!is.null(toPlace)) query_params[['toPlace']] <- toPlace
  if (!is.null(via)) query_params[['via']] <- via
  if (!is.null(viaMinimumStay)) query_params[['viaMinimumStay']] <- viaMinimumStay
  if (!is.null(time)) query_params[['time']] <- time
  if (!is.null(maxTransfers)) query_params[['maxTransfers']] <- maxTransfers
  if (!is.null(maxTravelTime)) query_params[['maxTravelTime']] <- maxTravelTime
  if (!is.null(minTransferTime)) query_params[['minTransferTime']] <- minTransferTime
  if (!is.null(additionalTransferTime)) query_params[['additionalTransferTime']] <- additionalTransferTime
  if (!is.null(transferTimeFactor)) query_params[['transferTimeFactor']] <- transferTimeFactor
  if (!is.null(maxMatchingDistance)) query_params[['maxMatchingDistance']] <- maxMatchingDistance
  if (!is.null(pedestrianProfile)) query_params[['pedestrianProfile']] <- pedestrianProfile
  if (!is.null(pedestrianSpeed)) query_params[['pedestrianSpeed']] <- pedestrianSpeed
  if (!is.null(cyclingSpeed)) query_params[['cyclingSpeed']] <- cyclingSpeed
  if (!is.null(elevationCosts)) query_params[['elevationCosts']] <- elevationCosts
  if (!is.null(useRoutedTransfers)) query_params[['useRoutedTransfers']] <- useRoutedTransfers
  if (!is.null(detailedTransfers)) query_params[['detailedTransfers']] <- detailedTransfers
  if (!is.null(joinInterlinedLegs)) query_params[['joinInterlinedLegs']] <- joinInterlinedLegs
  if (!is.null(transitModes)) query_params[['transitModes']] <- transitModes
  if (!is.null(directModes)) query_params[['directModes']] <- directModes
  if (!is.null(preTransitModes)) query_params[['preTransitModes']] <- preTransitModes
  if (!is.null(postTransitModes)) query_params[['postTransitModes']] <- postTransitModes
  if (!is.null(directRentalFormFactors)) query_params[['directRentalFormFactors']] <- directRentalFormFactors
  if (!is.null(preTransitRentalFormFactors)) query_params[['preTransitRentalFormFactors']] <- preTransitRentalFormFactors
  if (!is.null(postTransitRentalFormFactors)) query_params[['postTransitRentalFormFactors']] <- postTransitRentalFormFactors
  if (!is.null(directRentalPropulsionTypes)) query_params[['directRentalPropulsionTypes']] <- directRentalPropulsionTypes
  if (!is.null(preTransitRentalPropulsionTypes)) query_params[['preTransitRentalPropulsionTypes']] <- preTransitRentalPropulsionTypes
  if (!is.null(postTransitRentalPropulsionTypes)) query_params[['postTransitRentalPropulsionTypes']] <- postTransitRentalPropulsionTypes
  if (!is.null(directRentalProviders)) query_params[['directRentalProviders']] <- directRentalProviders
  if (!is.null(directRentalProviderGroups)) query_params[['directRentalProviderGroups']] <- directRentalProviderGroups
  if (!is.null(preTransitRentalProviders)) query_params[['preTransitRentalProviders']] <- preTransitRentalProviders
  if (!is.null(preTransitRentalProviderGroups)) query_params[['preTransitRentalProviderGroups']] <- preTransitRentalProviderGroups
  if (!is.null(postTransitRentalProviders)) query_params[['postTransitRentalProviders']] <- postTransitRentalProviders
  if (!is.null(postTransitRentalProviderGroups)) query_params[['postTransitRentalProviderGroups']] <- postTransitRentalProviderGroups
  if (!is.null(ignoreDirectRentalReturnConstraints)) query_params[['ignoreDirectRentalReturnConstraints']] <- ignoreDirectRentalReturnConstraints
  if (!is.null(ignorePreTransitRentalReturnConstraints)) query_params[['ignorePreTransitRentalReturnConstraints']] <- ignorePreTransitRentalReturnConstraints
  if (!is.null(ignorePostTransitRentalReturnConstraints)) query_params[['ignorePostTransitRentalReturnConstraints']] <- ignorePostTransitRentalReturnConstraints
  if (!is.null(numItineraries)) query_params[['numItineraries']] <- numItineraries
  if (!is.null(maxItineraries)) query_params[['maxItineraries']] <- maxItineraries
  if (!is.null(pageCursor)) query_params[['pageCursor']] <- pageCursor
  if (!is.null(timetableView)) query_params[['timetableView']] <- timetableView
  if (!is.null(arriveBy)) query_params[['arriveBy']] <- arriveBy
  if (!is.null(searchWindow)) query_params[['searchWindow']] <- searchWindow
  if (!is.null(requireBikeTransport)) query_params[['requireBikeTransport']] <- requireBikeTransport
  if (!is.null(requireCarTransport)) query_params[['requireCarTransport']] <- requireCarTransport
  if (!is.null(maxPreTransitTime)) query_params[['maxPreTransitTime']] <- maxPreTransitTime
  if (!is.null(maxPostTransitTime)) query_params[['maxPostTransitTime']] <- maxPostTransitTime
  if (!is.null(maxDirectTime)) query_params[['maxDirectTime']] <- maxDirectTime
  if (!is.null(fastestDirectFactor)) query_params[['fastestDirectFactor']] <- fastestDirectFactor
  if (!is.null(timeout)) query_params[['timeout']] <- timeout
  if (!is.null(passengers)) query_params[['passengers']] <- passengers
  if (!is.null(luggage)) query_params[['luggage']] <- luggage
  if (!is.null(slowDirect)) query_params[['slowDirect']] <- slowDirect
  if (!is.null(fastestSlowDirectFactor)) query_params[['fastestSlowDirectFactor']] <- fastestSlowDirectFactor
  if (!is.null(withFares)) query_params[['withFares']] <- withFares
  if (!is.null(withScheduledSkippedStops)) query_params[['withScheduledSkippedStops']] <- withScheduledSkippedStops
  if (!is.null(language)) query_params[['language']] <- language
  if (!is.null(algorithm)) query_params[['algorithm']] <- algorithm
  if (length(query_params) > 0) {
    req <- do.call(httr2::req_url_query, c(list(req), query_params))
  }



  # --- Control arguments ---
  auth <- .auth %||% default_auth
  if (!is.null(auth)) {
    if (is.character(auth)) {
      req <- httr2::req_auth_bearer_token(req, auth)
    } else if (is.function(auth)) {
      req <- auth(req)
    } else {
      stop('`.auth` must be a token string or a function(req) that returns a request.', call. = FALSE)
    }
  }

  headers <- default_headers
  if (!is.null(.headers)) headers <- c(headers, .headers)
  if (!is.null(headers)) req <- do.call(httr2::req_headers, c(list(req), headers))
  # Ensure Accept exists
  if (is.null(headers) || !any(tolower(names(headers)) == 'accept')) req <- httr2::req_headers(req, Accept = '*/*')

  referer <- .referer %||% default_referer
  if (!is.null(referer)) req <- httr2::req_headers(req, Referer = referer)

  throttle_rate <- .throttle_rate %||% default_throttle_rate
  if (!is.null(throttle_rate)) req <- httr2::req_throttle(req, rate = throttle_rate)

  req_opts <- .req_options %||% default_req_options
  if (!is.null(req_opts)) {
    if (!is.list(req_opts)) stop('`.req_options` must be a named list.', call. = FALSE)
    req <- do.call(httr2::req_options, c(list(req), req_opts))
  }

  build_only <- .build_only %||% default_build_only
  if (isTRUE(build_only)) return(req)

  paginate <- .paginate %||% NULL
  if (!is.null(paginate)) {
    resps <- oa3_paginate(req, paginate)
    # If pagination is used, we return the list of responses (parsed or raw)
    # For now, we return the raw list of responses if return_as='raw',
    # otherwise we try to parse each one.
    
    return_as <- .return_as %||% default_return_as
    return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
    
    if (return_as == 'raw') return(resps)
    
    json_parser <- .json_parser %||% default_json_parser
    json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
    
    return(lapply(resps, function(resp) {
      switch(return_as,
        'string' = httr2::resp_body_string(resp),
        'list' = switch(
          json_parser,
          'RcppSimdJson' = {
             if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
               httr2::resp_body_json(resp)
             } else {
               RcppSimdJson::fparse(httr2::resp_body_string(resp))
             }
          },
          'jsonlite' = httr2::resp_body_json(resp),
          stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
        ),
        stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
      )
    }))
  }

  resp <- httr2::req_perform(req)

  handler <- .handle_response %||% default_handle_response
  if (!is.null(handler) && is.function(handler)) return(handler(resp))

  # Robust response handling
  return_as <- .return_as %||% default_return_as
  return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
  json_parser <- .json_parser %||% default_json_parser
  json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
  switch(return_as,
    'raw' = return(resp),
    'string' = return(httr2::resp_body_string(resp)),
    'list' = switch(
      json_parser,
      'RcppSimdJson' = {
        if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
          return(httr2::resp_body_json(resp))
        }
        RcppSimdJson::fparse(httr2::resp_body_string(resp))
      },
      'jsonlite' = httr2::resp_body_json(resp),
      stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
    ),
    stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
  )
}

