# Generated by the openapi3 package: do not edit by hand
# Source: openapi.yaml

#' Get a list of rental providers or all rental stations and vehicles for
#' a map section or provider
#'
#' @description
#' Various options to filter the providers, stations and vehicles are
#' available. If none of these filters are provided, a list of all
#' available rental providers is returned without any station, vehicle or
#' zone data.
#' 
#' At least one of the following filters must be provided to retrieve
#' station, vehicle and zone data:
#' 
#' - A bounding box defined by the `min` and `max` parameters
#' - A circle defined by the `point` and `radius` parameters
#' - A list of provider groups via the `providerGroups` parameter
#' - A list of providers via the `providers` parameter
#' 
#' Only data that matches all the provided filters is returned.
#' 
#' Provide the `withProviders=false` parameter to retrieve only provider
#' groups if detailed feed information is not required.
#'
#' @param min latitude,longitude pair of the lower right coordinate
#' 
#' @param max latitude,longitude pair of the upper left coordinate
#' 
#' @param point `latitude,longitude[,level]` tuple with
#' - latitude and longitude in degrees
#' - (optional) level: the OSM level (ignored, for compatibility reasons)
#' 
#' OR
#' 
#' stop id
#' @param radius Radius around `point` in meters.
#' 
#' @param providerGroups A list of rental provider groups to return.
#' If both `providerGroups` and `providers` are empty/not specified,
#' all providers in the map section are returned.
#' @param providers A list of rental providers to return.
#' If both `providerGroups` and `providers` are empty/not specified,
#' all providers in the map section are returned.
#' @param withProviders Optional. Include providers in output. If false, only provider
#' groups are returned.
#' 
#' Also affects the providers list for each provider group.
#' @param withStations Optional. Include stations in output (requires at least min+max or providers filter).
#' 
#' @param withVehicles Optional. Include free-floating vehicles in output (requires at least min+max or providers filter).
#' 
#' @param withZones Optional. Include geofencing zones in output (requires at least min+max or providers filter).
#' 
#' @param .return_as A string specifying the return format. Defaults to 'list'. Options are 'list' for a parsed R list, 'raw' for the raw httr2_response object, or 'string' for the raw JSON string.
#' @param .json_parser A string specifying which parser to use when .return_as = 'list'. Defaults to 'RcppSimdJson' (faster) or 'jsonlite'. Beware that their output may differ slightly.
#' @param .headers A named list of extra HTTP headers to add to the request. If no 'Accept' header is provided anywhere, 'Accept: */*' will be sent by default.
#' @param .auth An authentication token or method (e.g., a bearer token string).
#' @param .throttle_rate A number to pass to `httr2::req_throttle()` to limit the rate of requests. For example, `15/60` means 15 requests per minute. This overrides any default rate set at client generation time.
#' @param .build_only A logical. If TRUE, the function will build and return the httr2_request object without performing it. Defaults to FALSE.
#' @param .server A string to override the base URL for this specific request. If provided, it will be used instead of the default server URL.
#' @param .endpoint A string to override the path for this specific request. If provided, it will be used instead of the default path from the specification. For example, use '/v2/users' to override the endpoint path.
#' @param .referer A string to set the Referer HTTP header.
#' @param .req_options A named list of curl options passed to `httr2::req_options()`. Useful for timeouts, proxies, SSL, etc.
#' @param .handle_response A function taking an `httr2_response` and returning a value. If supplied, it overrides `.return_as` / `.json_parser` handling. See helpers like `oa3_content_or_stop()`.
#' @param .json_auto_unbox Logical. If TRUE, JSON bodies are encoded with `auto_unbox = TRUE` (jsonlite). Defaults to FALSE unless overridden.
#' @param .paginate A logical, character string, or function to enable pagination. If TRUE (or "link_header"), uses Link headers. Other options: "page_param", "cursor_param", or a custom function. See `oa3_paginate()`.
#' @export
mc_rentals <- function(min = NULL, max = NULL, point = NULL, radius = NULL, providerGroups = NULL, providers = NULL, withProviders = NULL, withStations = NULL, withVehicles = NULL, withZones = NULL, .return_as = NULL, .json_parser = NULL, .headers = NULL, .auth = NULL, .throttle_rate = NULL, .build_only = NULL, .server = NULL, .endpoint = NULL, .referer = NULL, .req_options = NULL, .handle_response = NULL, .json_auto_unbox = NULL, .paginate = NULL) {
  # --- Self-contained Default Arguments ---
  default_return_as <- "raw"
  default_json_parser <- "RcppSimdJson"
  default_headers <- list(Accept = "*/*")
  default_auth <- NULL
  default_throttle_rate <- NULL
  default_build_only <- TRUE
  default_server <- "http://localhost:8080"
  default_referer <- NULL
  default_req_options <- NULL
  default_json_auto_unbox <- TRUE
  default_handle_response <- NULL

  # --- Request building ---
  server_url <- .server %||% default_server
  req <- httr2::request(server_url)
  req <- httr2::req_method(req, method = "GET")

  # Path parameters
  path_params <- list()
  path_template <- .endpoint %||% "/api/v1/rentals"
  if (length(path_params)) {
    # URL-encode each path value
    for (nm in names(path_params)) path_params[[nm]] <- curl::curl_escape(as.character(path_params[[nm]]))
  }
  path_expanded <- as.character(glue::glue_data(path_params, path_template))
  req <- httr2::req_url_path_append(req, path_expanded)

  # Query parameters
  query_params <- list()
  if (!is.null(min)) query_params[['min']] <- min
  if (!is.null(max)) query_params[['max']] <- max
  if (!is.null(point)) query_params[['point']] <- point
  if (!is.null(radius)) query_params[['radius']] <- radius
  if (!is.null(providerGroups)) query_params[['providerGroups']] <- providerGroups
  if (!is.null(providers)) query_params[['providers']] <- providers
  if (!is.null(withProviders)) query_params[['withProviders']] <- withProviders
  if (!is.null(withStations)) query_params[['withStations']] <- withStations
  if (!is.null(withVehicles)) query_params[['withVehicles']] <- withVehicles
  if (!is.null(withZones)) query_params[['withZones']] <- withZones
  if (length(query_params) > 0) {
    req <- do.call(httr2::req_url_query, c(list(req), query_params))
  }



  # --- Control arguments ---
  auth <- .auth %||% default_auth
  if (!is.null(auth)) {
    if (is.character(auth)) {
      req <- httr2::req_auth_bearer_token(req, auth)
    } else if (is.function(auth)) {
      req <- auth(req)
    } else {
      stop('`.auth` must be a token string or a function(req) that returns a request.', call. = FALSE)
    }
  }

  headers <- default_headers
  if (!is.null(.headers)) headers <- c(headers, .headers)
  if (!is.null(headers)) req <- do.call(httr2::req_headers, c(list(req), headers))
  # Ensure Accept exists
  if (is.null(headers) || !any(tolower(names(headers)) == 'accept')) req <- httr2::req_headers(req, Accept = '*/*')

  referer <- .referer %||% default_referer
  if (!is.null(referer)) req <- httr2::req_headers(req, Referer = referer)

  throttle_rate <- .throttle_rate %||% default_throttle_rate
  if (!is.null(throttle_rate)) req <- httr2::req_throttle(req, rate = throttle_rate)

  req_opts <- .req_options %||% default_req_options
  if (!is.null(req_opts)) {
    if (!is.list(req_opts)) stop('`.req_options` must be a named list.', call. = FALSE)
    req <- do.call(httr2::req_options, c(list(req), req_opts))
  }

  build_only <- .build_only %||% default_build_only
  if (isTRUE(build_only)) return(req)

  paginate <- .paginate %||% NULL
  if (!is.null(paginate)) {
    resps <- oa3_paginate(req, paginate)
    # If pagination is used, we return the list of responses (parsed or raw)
    # For now, we return the raw list of responses if return_as='raw',
    # otherwise we try to parse each one.
    
    return_as <- .return_as %||% default_return_as
    return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
    
    if (return_as == 'raw') return(resps)
    
    json_parser <- .json_parser %||% default_json_parser
    json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
    
    return(lapply(resps, function(resp) {
      switch(return_as,
        'string' = httr2::resp_body_string(resp),
        'list' = switch(
          json_parser,
          'RcppSimdJson' = {
             if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
               httr2::resp_body_json(resp)
             } else {
               RcppSimdJson::fparse(httr2::resp_body_string(resp))
             }
          },
          'jsonlite' = httr2::resp_body_json(resp),
          stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
        ),
        stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
      )
    }))
  }

  resp <- httr2::req_perform(req)

  handler <- .handle_response %||% default_handle_response
  if (!is.null(handler) && is.function(handler)) return(handler(resp))

  # Robust response handling
  return_as <- .return_as %||% default_return_as
  return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
  json_parser <- .json_parser %||% default_json_parser
  json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
  switch(return_as,
    'raw' = return(resp),
    'string' = return(httr2::resp_body_string(resp)),
    'list' = switch(
      json_parser,
      'RcppSimdJson' = {
        if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
          return(httr2::resp_body_json(resp))
        }
        RcppSimdJson::fparse(httr2::resp_body_string(resp))
      },
      'jsonlite' = httr2::resp_body_json(resp),
      stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
    ),
    stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
  )
}

