# Generated by the openapi3 package: do not edit by hand
# Source: openapi.yaml

#' Get the next N departures or arrivals of a stop sorted by time
#'
#' @param stopId stop id of the stop to retrieve departures/arrivals for
#' 
#' @param center Anchor coordinate. Format: latitude,longitude pair.
#' Used as fallback when "stopId" is missing or can't be found.
#' If both are provided and "stopId" resolves, "stopId" is used.
#' If "stopId" does not resolve, "center" is used instead. "radius" is
#' required when querying by "center" (i.e. without a valid "stopId").
#' @param time Optional. Defaults to the current time.
#' 
#' @param arriveBy Optional. Default is `false`.
#' 
#' - `arriveBy=true`: the parameters `date` and `time` refer to the arrival time
#' - `arriveBy=false`: the parameters `date` and `time` refer to the departure time
#' @param direction This parameter will be ignored in case `pageCursor` is set.
#' 
#' Optional. Default is
#' - `LATER` for `arriveBy=false`
#' - `EARLIER` for `arriveBy=true`
#' 
#' The response will contain the next `n` arrivals / departures
#' in case `EARLIER` is selected and the previous `n`
#' arrivals / departures if `LATER` is selected.
#'
#' Allowed values: EARLIER, LATER.
#' @param window Optional. Window in seconds around `time`.
#' Limiting the response to those that are at most `window` seconds aways in time.
#' If both `n` and `window` are set, it uses whichever returns more.
#' @param mode Optional. Default is all transit modes.
#' 
#' Only return arrivals/departures of the given modes.
#'
#' Allowed values: WALK, BIKE, RENTAL, CAR, CAR_PARKING, CAR_DROPOFF, ODM, RIDE_SHARING, FLEX, DEBUG_BUS_ROUTE, DEBUG_RAILWAY_ROUTE, DEBUG_FERRY_ROUTE, TRANSIT, TRAM, SUBWAY, FERRY, AIRPLANE, BUS, COACH, RAIL, HIGHSPEED_RAIL, LONG_DISTANCE, NIGHT_RAIL, REGIONAL_FAST_RAIL, REGIONAL_RAIL, SUBURBAN, FUNICULAR, AERIAL_LIFT, OTHER, AREAL_LIFT, METRO, CABLE_CAR.
#' @param FALSE. Minimum number of events to return. If both `n` and `window`
#' are provided, the API uses whichever returns more events.
#' @param radius Optional. Radius in meters.
#' 
#' Default is that only stop times of the parent of the stop itself
#' and all stops with the same name (+ their child stops) are returned.
#' 
#' If set, all stops at parent stations and their child stops in the specified radius
#' are returned.
#' @param exactRadius Optional. Default is `false`.
#' 
#' If set to `true`, only stations that are phyiscally in the radius are considered.
#' If set to `false`, additionally to the stations in the radius, equivalences with the same name and children are considered.
#' @param fetchStops Experimental. Expect unannounced breaking changes (without version bumps).
#' 
#' Optional. Default is `false`. If set to `true`, the following stops are returned
#' for departures and the previous stops are returned for arrivals.
#' @param pageCursor Use the cursor to go to the next "page" of stop times.
#' Copy the cursor from the last response and keep the original request as is.
#' This will enable you to search for stop times in the next or previous time-window.
#' @param withScheduledSkippedStops Optional. Include stoptimes where passengers can not alight/board according to schedule.
#' 
#' @param language language tags as used in OpenStreetMap / GTFS
#' (usually BCP-47 / ISO 639-1, or ISO 639-2 if there's no ISO 639-1)
#' @param withAlerts Optional. Default is `true`. If set to `false`, alerts are omitted in the metadata of place for all stopTimes.
#' 
#' @param .return_as A string specifying the return format. Defaults to 'list'. Options are 'list' for a parsed R list, 'raw' for the raw httr2_response object, or 'string' for the raw JSON string.
#' @param .json_parser A string specifying which parser to use when .return_as = 'list'. Defaults to 'RcppSimdJson' (faster) or 'jsonlite'. Beware that their output may differ slightly.
#' @param .headers A named list of extra HTTP headers to add to the request. If no 'Accept' header is provided anywhere, 'Accept: */*' will be sent by default.
#' @param .auth An authentication token or method (e.g., a bearer token string).
#' @param .throttle_rate A number to pass to `httr2::req_throttle()` to limit the rate of requests. For example, `15/60` means 15 requests per minute. This overrides any default rate set at client generation time.
#' @param .build_only A logical. If TRUE, the function will build and return the httr2_request object without performing it. Defaults to FALSE.
#' @param .server A string to override the base URL for this specific request. If provided, it will be used instead of the default server URL.
#' @param .endpoint A string to override the path for this specific request. If provided, it will be used instead of the default path from the specification. For example, use '/v2/users' to override the endpoint path.
#' @param .referer A string to set the Referer HTTP header.
#' @param .req_options A named list of curl options passed to `httr2::req_options()`. Useful for timeouts, proxies, SSL, etc.
#' @param .handle_response A function taking an `httr2_response` and returning a value. If supplied, it overrides `.return_as` / `.json_parser` handling. See helpers like `oa3_content_or_stop()`.
#' @param .json_auto_unbox Logical. If TRUE, JSON bodies are encoded with `auto_unbox = TRUE` (jsonlite). Defaults to FALSE unless overridden.
#' @param .paginate A logical, character string, or function to enable pagination. If TRUE (or "link_header"), uses Link headers. Other options: "page_param", "cursor_param", or a custom function. See `oa3_paginate()`.
#' @export
mc_stoptimes <- function(stopId = NULL, center = NULL, time = NULL, arriveBy = NULL, direction = NULL, window = NULL, mode = NULL, FALSE. = NULL, radius = NULL, exactRadius = NULL, fetchStops = NULL, pageCursor = NULL, withScheduledSkippedStops = NULL, language = NULL, withAlerts = NULL, .return_as = NULL, .json_parser = NULL, .headers = NULL, .auth = NULL, .throttle_rate = NULL, .build_only = NULL, .server = NULL, .endpoint = NULL, .referer = NULL, .req_options = NULL, .handle_response = NULL, .json_auto_unbox = NULL, .paginate = NULL) {
  # --- Self-contained Default Arguments ---
  default_return_as <- "raw"
  default_json_parser <- "RcppSimdJson"
  default_headers <- list(Accept = "*/*")
  default_auth <- NULL
  default_throttle_rate <- NULL
  default_build_only <- TRUE
  default_server <- "http://localhost:8080"
  default_referer <- NULL
  default_req_options <- NULL
  default_json_auto_unbox <- TRUE
  default_handle_response <- NULL

  # --- Request building ---
  server_url <- .server %||% default_server
  req <- httr2::request(server_url)
  req <- httr2::req_method(req, method = "GET")

  # Path parameters
  path_params <- list()
  path_template <- .endpoint %||% "/api/v5/stoptimes"
  if (length(path_params)) {
    # URL-encode each path value
    for (nm in names(path_params)) path_params[[nm]] <- curl::curl_escape(as.character(path_params[[nm]]))
  }
  path_expanded <- as.character(glue::glue_data(path_params, path_template))
  req <- httr2::req_url_path_append(req, path_expanded)

  # Query parameters
  query_params <- list()
  if (!is.null(stopId)) query_params[['stopId']] <- stopId
  if (!is.null(center)) query_params[['center']] <- center
  if (!is.null(time)) query_params[['time']] <- time
  if (!is.null(arriveBy)) query_params[['arriveBy']] <- arriveBy
  if (!is.null(direction)) query_params[['direction']] <- direction
  if (!is.null(window)) query_params[['window']] <- window
  if (!is.null(mode)) query_params[['mode']] <- mode
  if (!is.null(FALSE.)) query_params[['FALSE']] <- FALSE.
  if (!is.null(radius)) query_params[['radius']] <- radius
  if (!is.null(exactRadius)) query_params[['exactRadius']] <- exactRadius
  if (!is.null(fetchStops)) query_params[['fetchStops']] <- fetchStops
  if (!is.null(pageCursor)) query_params[['pageCursor']] <- pageCursor
  if (!is.null(withScheduledSkippedStops)) query_params[['withScheduledSkippedStops']] <- withScheduledSkippedStops
  if (!is.null(language)) query_params[['language']] <- language
  if (!is.null(withAlerts)) query_params[['withAlerts']] <- withAlerts
  if (length(query_params) > 0) {
    req <- do.call(httr2::req_url_query, c(list(req), query_params))
  }



  # --- Control arguments ---
  auth <- .auth %||% default_auth
  if (!is.null(auth)) {
    if (is.character(auth)) {
      req <- httr2::req_auth_bearer_token(req, auth)
    } else if (is.function(auth)) {
      req <- auth(req)
    } else {
      stop('`.auth` must be a token string or a function(req) that returns a request.', call. = FALSE)
    }
  }

  headers <- default_headers
  if (!is.null(.headers)) headers <- c(headers, .headers)
  if (!is.null(headers)) req <- do.call(httr2::req_headers, c(list(req), headers))
  # Ensure Accept exists
  if (is.null(headers) || !any(tolower(names(headers)) == 'accept')) req <- httr2::req_headers(req, Accept = '*/*')

  referer <- .referer %||% default_referer
  if (!is.null(referer)) req <- httr2::req_headers(req, Referer = referer)

  throttle_rate <- .throttle_rate %||% default_throttle_rate
  if (!is.null(throttle_rate)) req <- httr2::req_throttle(req, rate = throttle_rate)

  req_opts <- .req_options %||% default_req_options
  if (!is.null(req_opts)) {
    if (!is.list(req_opts)) stop('`.req_options` must be a named list.', call. = FALSE)
    req <- do.call(httr2::req_options, c(list(req), req_opts))
  }

  build_only <- .build_only %||% default_build_only
  if (isTRUE(build_only)) return(req)

  paginate <- .paginate %||% NULL
  if (!is.null(paginate)) {
    resps <- oa3_paginate(req, paginate)
    # If pagination is used, we return the list of responses (parsed or raw)
    # For now, we return the raw list of responses if return_as='raw',
    # otherwise we try to parse each one.
    
    return_as <- .return_as %||% default_return_as
    return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
    
    if (return_as == 'raw') return(resps)
    
    json_parser <- .json_parser %||% default_json_parser
    json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
    
    return(lapply(resps, function(resp) {
      switch(return_as,
        'string' = httr2::resp_body_string(resp),
        'list' = switch(
          json_parser,
          'RcppSimdJson' = {
             if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
               httr2::resp_body_json(resp)
             } else {
               RcppSimdJson::fparse(httr2::resp_body_string(resp))
             }
          },
          'jsonlite' = httr2::resp_body_json(resp),
          stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
        ),
        stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
      )
    }))
  }

  resp <- httr2::req_perform(req)

  handler <- .handle_response %||% default_handle_response
  if (!is.null(handler) && is.function(handler)) return(handler(resp))

  # Robust response handling
  return_as <- .return_as %||% default_return_as
  return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
  json_parser <- .json_parser %||% default_json_parser
  json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
  switch(return_as,
    'raw' = return(resp),
    'string' = return(httr2::resp_body_string(resp)),
    'list' = switch(
      json_parser,
      'RcppSimdJson' = {
        if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
          return(httr2::resp_body_json(resp))
        }
        RcppSimdJson::fparse(httr2::resp_body_string(resp))
      },
      'jsonlite' = httr2::resp_body_json(resp),
      stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
    ),
    stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
  )
}

