# Generated by the openapi3 package: do not edit by hand
# Source: openapi.yaml

#' Get the next N departures or arrivals of a stop sorted by time
#'
#' @param stopId stop id of the stop to retrieve departures/arrivals for
#' 
#' @param time Optional. Defaults to the current time.
#' 
#' @param arriveBy Optional. Default is `false`.
#' 
#' - `arriveBy=true`: the parameters `date` and `time` refer to the arrival time
#' - `arriveBy=false`: the parameters `date` and `time` refer to the departure time
#' @param direction This parameter will be ignored in case `pageCursor` is set.
#' 
#' Optional. Default is
#' - `LATER` for `arriveBy=false`
#' - `EARLIER` for `arriveBy=true`
#' 
#' The response will contain the next `n` arrivals / departures
#' in case `EARLIER` is selected and the previous `n`
#' arrivals / departures if `LATER` is selected.
#'
#' Allowed values: EARLIER, LATER.
#' @param mode Optional. Default is all transit modes.
#' 
#' Only return arrivals/departures of the given modes.
#'
#' Allowed values: WALK, BIKE, RENTAL, CAR, CAR_PARKING, CAR_DROPOFF, ODM, FLEX, TRANSIT, TRAM, SUBWAY, FERRY, AIRPLANE, METRO, BUS, COACH, RAIL, HIGHSPEED_RAIL, LONG_DISTANCE, NIGHT_RAIL, REGIONAL_FAST_RAIL, REGIONAL_RAIL, CABLE_CAR, FUNICULAR, AREAL_LIFT, OTHER.
#' @param FALSE. the number of events
#' 
#' @param radius Optional. Radius in meters.
#' 
#' Default is that only stop times of the parent of the stop itself
#' and all stops with the same name (+ their child stops) are returned.
#' 
#' If set, all stops at parent stations and their child stops in the specified radius
#' are returned.
#' @param exactRadius Optional. Default is `false`.
#' 
#' If set to `true`, only stations that are phyiscally in the radius are considered.
#' If set to `false`, additionally to the stations in the radius, equivalences with the same name and children are considered.
#' @param pageCursor Use the cursor to go to the next "page" of stop times.
#' Copy the cursor from the last response and keep the original request as is.
#' This will enable you to search for stop times in the next or previous time-window.
#' @param withScheduledSkippedStops Optional. Include stoptimes where passengers can not alight/board according to schedule.
#' 
#' @param language language tags as used in OpenStreetMap / GTFS
#' (usually BCP-47 / ISO 639-1, or ISO 639-2 if there's no ISO 639-1)
#' @param .return_as How to return the response. One of 'list' (default), 'string', or 'raw'.
#' @param .json_parser JSON parser when `.return_as = 'list'`. One of 'RcppSimdJson' (default) or 'jsonlite'.
#' @param .headers Named list of additional HTTP headers to include.
#' @param .auth Bearer token string or a function `function(req) req` to apply custom auth.
#' @param .throttle_rate Requests per second (numeric). If set, throttling is applied.
#' @param .build_only If TRUE, return the unperformed request object.
#' @param .server Override the server URL for this call.
#' @param .endpoint A string to override the path for this specific request (e.g., '/v2/users/{id}'). If provided, it will be used instead of the default path from the specification.
#' @param .referer Optional Referer header value.
#' @param .req_options Named list of curl options passed to `httr2::req_options()`.
#' @param .handle_response Optional function `function(resp) ...` to post-process the response.
#' @param .json_auto_unbox If TRUE (default), auto-unbox scalar JSON values for request bodies.
#' @export
mc_stoptimes <- function(stopId = NULL, time = NULL, arriveBy = NULL, direction = NULL, mode = NULL, FALSE. = NULL, radius = NULL, exactRadius = NULL, pageCursor = NULL, withScheduledSkippedStops = NULL, language = NULL, .return_as = NULL, .json_parser = NULL, .headers = NULL, .auth = NULL, .throttle_rate = NULL, .build_only = NULL, .server = NULL, .endpoint = NULL, .referer = NULL, .req_options = NULL, .handle_response = NULL, .json_auto_unbox = NULL) {
  # --- Self-contained Default Arguments ---
  default_return_as <- "raw"
  default_json_parser <- "RcppSimdJson"
  default_headers <- list(Accept = "*/*")
  default_auth <- NULL
  default_throttle_rate <- NULL
  default_build_only <- TRUE
  default_server <- "http://localhost:8080"
  default_referer <- NULL
  default_req_options <- NULL
  default_json_auto_unbox <- TRUE
  default_handle_response <- NULL

  # --- Request building ---
  server_url <- .server %||% default_server
  req <- httr2::request(server_url)
  req <- httr2::req_method(req, method = "GET")

  # Path parameters
  path_params <- list()
  path_template <- .endpoint %||% "/api/v4/stoptimes"
  if (length(path_params)) {
    # URL-encode each path value
    for (nm in names(path_params)) path_params[[nm]] <- curl::curl_escape(as.character(path_params[[nm]]))
  }
  path_expanded <- as.character(glue::glue_data(path_params, path_template))
  req <- httr2::req_url_path_append(req, path_expanded)

  # Query parameters
  query_params <- list()
  if (!is.null(stopId)) query_params[['stopId']] <- stopId
  if (!is.null(time)) query_params[['time']] <- time
  if (!is.null(arriveBy)) query_params[['arriveBy']] <- arriveBy
  if (!is.null(direction)) query_params[['direction']] <- direction
  if (!is.null(mode)) query_params[['mode']] <- mode
  if (!is.null(FALSE.)) query_params[['FALSE']] <- FALSE.
  if (!is.null(radius)) query_params[['radius']] <- radius
  if (!is.null(exactRadius)) query_params[['exactRadius']] <- exactRadius
  if (!is.null(pageCursor)) query_params[['pageCursor']] <- pageCursor
  if (!is.null(withScheduledSkippedStops)) query_params[['withScheduledSkippedStops']] <- withScheduledSkippedStops
  if (!is.null(language)) query_params[['language']] <- language
  if (length(query_params) > 0) {
    req <- do.call(httr2::req_url_query, c(list(req), query_params))
  }



  # --- Control arguments ---
  auth <- .auth %||% default_auth
  if (!is.null(auth)) {
    if (is.character(auth)) {
      req <- httr2::req_auth_bearer_token(req, auth)
    } else if (is.function(auth)) {
      req <- auth(req)
    } else {
      stop('`.auth` must be a token string or a function(req) that returns a request.', call. = FALSE)
    }
  }

  headers <- default_headers
  if (!is.null(.headers)) headers <- c(headers, .headers)
  if (!is.null(headers)) req <- do.call(httr2::req_headers, c(list(req), headers))
  # Ensure Accept exists
  if (is.null(headers) || !any(tolower(names(headers)) == 'accept')) req <- httr2::req_headers(req, Accept = '*/*')

  referer <- .referer %||% default_referer
  if (!is.null(referer)) req <- httr2::req_headers(req, Referer = referer)

  throttle_rate <- .throttle_rate %||% default_throttle_rate
  if (!is.null(throttle_rate)) req <- httr2::req_throttle(req, rate = throttle_rate)

  req_opts <- .req_options %||% default_req_options
  if (!is.null(req_opts)) {
    if (!is.list(req_opts)) stop('`.req_options` must be a named list.', call. = FALSE)
    req <- do.call(httr2::req_options, c(list(req), req_opts))
  }

  build_only <- .build_only %||% default_build_only
  if (isTRUE(build_only)) return(req)

  resp <- httr2::req_perform(req)

  handler <- .handle_response %||% default_handle_response
  if (!is.null(handler) && is.function(handler)) return(handler(resp))

  # Robust response handling
  return_as <- .return_as %||% default_return_as
  return_as <- if (is.null(return_as)) 'list' else as.character(return_as)[1L]
  json_parser <- .json_parser %||% default_json_parser
  json_parser <- if (is.null(json_parser)) 'RcppSimdJson' else as.character(json_parser)[1L]
  switch(return_as,
    'raw' = return(resp),
    'string' = return(httr2::resp_body_string(resp)),
    'list' = switch(
      json_parser,
      'RcppSimdJson' = {
        if (!requireNamespace('RcppSimdJson', quietly = TRUE)) {
          return(httr2::resp_body_json(resp))
        }
        RcppSimdJson::fparse(httr2::resp_body_string(resp))
      },
      'jsonlite' = httr2::resp_body_json(resp),
      stop("Unknown .json_parser: '", json_parser, "'.", call. = FALSE)
    ),
    stop("Unknown .return_as: '", return_as, "'.", call. = FALSE)
  )
}

